<a href="https://colab.research.google.com/github/sherbw28/class_deep/blob/main/0920%E9%96%A2%E6%95%B0%E5%AE%9A%E7%BE%A9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# python3で関数を定義する
関数定義

In [1]:
def hello():
  print("hello kansu")

In [2]:
hello()

hello kansu


# 引数付きの関数を定義する

In [3]:
def hello(who):
  print(f'{who} sent you message')

hello("Eisuke")

Eisuke sent you message


# 複数の引数つきの関数を定義

In [4]:
def hello(who,aisatu):
  print(f'{who} say {aisatu}')

hello("Eisuke","Hello")

Eisuke say Hello


# 関数の戻り値を定義する
戻り値1つの関数を定義

In [5]:
def helloBack(who,ai):
  return print(who + ai)
a = helloBack("aaa","bbb")
a

aaabbb


# 複数の戻り値を返す関数を定義

In [6]:
def keisan(x,y):
  return x,y,x+y

# その他の文法
分岐(if文)

# リスト、キーワード

In [8]:
def include(list,keyword):
  uniq = set(list)
  if keyword in uniq:
    print(keyword)
  else:
    print(keyword + "が含まれない")

list1 = ["アップル","ペン","ペン","パイナップル"]

# 繰り返し分(while文)

In [9]:
def cont(max):
  num = 0
  while num < max:
    num += 1

# 繰り返し分(for文)
変数βの集合から1つずつ取り出す
for 変数α in range(変数β):

In [10]:
def every(array):
  for x in array:
    print(x)

  list = [1,2,3]
  tuple = (4,5,6)
  dict = {"a":7,"b":8,"c":9}
  every(dict)

# カウンター変数で繰り返す

# 繰り返しを中断したいときは、break命令

In [11]:
def stop(array):
  for i in array:
    if i > 4:
      break
    print(i)
list = [1,2,3,4,5,1,2,3,4,5]

# 繰り返しをスキップしたいときは、continue命令

In [12]:
def skip(array):
  for i in array:
    if i > 4:
      continue
    print(i)

list = [1,2,3,4,5,1,2,3,4,5]
skip(list)

1
2
3
4
1
2
3
4


### 多次元のndarrayへのスライスでの代入

In [22]:
 import numpy as np
 a = np.arange(12).reshape(3,4)
 print(a)
 print(a[1:,1:3])
 a[1:,1:3] = 100
 print(a)
 a[1:,1:3] = [100, 200]
 print(a)

a[1:,1:3] = [[100,200],[300,400]]
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 5  6]
 [ 9 10]]
[[  0   1   2   3]
 [  4 100 100   7]
 [  8 100 100  11]]
[[  0   1   2   3]
 [  4 100 200   7]
 [  8 100 200  11]]
[[  0   1   2   3]
 [  4 100 200   7]
 [  8 300 400  11]]


### 多次元のndarrayへのstepを使ったスライスでの代入

In [28]:
a = np.arange(12).reshape((3,4))
print(a)
print(a[1:,::2])
print(a[:2,::3])
a[1:,::2] = [[100,200],[300,400]]
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 4  6]
 [ 8 10]]
[[0 3]
 [4 7]]
[[  0   1   2   3]
 [100   5 200   7]
 [300   9 400  11]]
